export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type DatabaseTable =
  | "profiles"
  | "settings"
  | "goals"
  | "roadmaps"
  | "milestones"
  | "focus_sessions"
  | "xp_progress"
  | "streaks"
  | "health_logs"
  | "sleep_logs"
  | "knowledge_entries"
  | "reflections"
  | "weekly_reviews"
  | "evolution_metrics"
  | "dashboard_widgets"
  | "genesis_master_roadmap"
  | "genesis_roadmap_connections"
  | "genesis_critical_dates"
  | "genesis_milestone_links"
  | "genesis_critical_reminders"
  | "knowledge_concepts"
  | "knowledge_reviews"
  | "concept_relationships"
  | "roadmap_concept_requirements"
  | "learning_velocity"
  | "deep_work_goals"
  | "deep_work_outcomes"
  | "cognitive_performance"
  | "health_scores"
  | "exec_regulation_state"
  | "adaptive_adjustments"
  | "recovery_sessions";
